### ISSUE TITLE
removing --headless causes 

### ISSUE THREAD

**Issue by torian257x** [derekmd/laravel-dusk-firefox#16]
![image](https://user-images.githubusercontent.com/2072058/128252829-93c8f700-a078-4540-b565-f7d35b786745.png)

>Your firefox profile cannot be loaded. It may be missing or inaccessible.

as a result, firefox doesn't open, nor does the test run

any fixes to this you know of?

**Comment by derekmd** [comment]
Package dependency "php-webdriver/webdriver" v1.11.0 stopped setting up a temporary Firefox profile: https://github.com/php-webdriver/php-webdriver/pull/890/files#diff-ffbfd51f39f3064af75d9fea1b50bbcde91fdd03aa429a7101c4416d1b43d802L293-L299

I think it now assumes you've manually opened a Firefox browser window at least once so a local profile already exists?

It can likely be fixed by programmatically setting up a profile in your application's `tests/DuskTestCase.php` file.

Add imports:

```php
use Facebook\WebDriver\Firefox\FirefoxDriver;
use Facebook\WebDriver\Firefox\FirefoxProfile;
use Facebook\WebDriver\Firefox\FirefoxPreferences;
```

Update the `driver()` method to assign a `FirefoxProfile` object:

```php
    protected function driver()
    {
        $options = (new FirefoxOptions)
            ->addArguments($this->filterHeadlessArguments([
                    '--headless',
                    '--window-size=1920,1080',
            ]))
            ->setPreference('devtools.console.stdout.content', true);

        $profile = (new FirefoxProfile)
           ->setPreference(FirefoxPreferences::READER_PARSE_ON_LOAD_ENABLED, false)
           ->setPreference(FirefoxPreferences::DEVTOOLS_JSONVIEW, false);

        return RemoteWebDriver::create(
            $_ENV['DUSK_DRIVER_URL'] ?? 'http://localhost:4444',
            DesiredCapabilities::firefox()
                ->setCapability(FirefoxOptions::CAPABILITY, $options)
                ->setCapability(FirefoxDriver::PROFILE, $profile)
        );
    }
```

**Comment by torian257x** [comment]
the thing is, I _have_ manually opened firefox already.

running this driver method:

```
    protected function driver()
    {
        $options = (new FirefoxOptions)
            ->addArguments($this->filterHeadlessArguments([
//                '--headless',
                '--window-size=1920,1080',
            ]))
            ->setPreference('devtools.console.stdout.content', true);

        $profile = (new FirefoxProfile)
            ->setPreference(FirefoxPreferences::READER_PARSE_ON_LOAD_ENABLED, false)
            ->setPreference(FirefoxPreferences::DEVTOOLS_JSONVIEW, false);

        return RemoteWebDriver::create(
            $_ENV['DUSK_DRIVER_URL'] ?? 'http://localhost:4444',
            DesiredCapabilities::firefox()
                ->setCapability(FirefoxOptions::CAPABILITY, $options)
                ->setCapability(FirefoxDriver::PROFILE, $profile)
        );
    }
```


still getting the popup

**Comment by torian257x** [comment]
adding the other preferences doesn't seem to make a difference

```
        $profile = (new FirefoxProfile)
            ->setPreference(FirefoxPreferences::READER_PARSE_ON_LOAD_ENABLED, false)
            ->setPreference(FirefoxPreferences::DEVTOOLS_JSONVIEW, false)
            ->setPreference(FirefoxPreferences::BROWSER_STARTUP_HOMEPAGE, 'https://bippo.com')
            ->setPreference(FirefoxPreferences::WEBDRIVER_FIREFOX_PORT, 4444);
```
still getting the error

**Comment by derekmd** [comment]
To capture the complete Geckodriver process output, comment out the phrases in `vendor/derekmd/laravel-dusk-firefox/src/Firefox/StdoutLog.php`:

```php
    public function getOutput()
    {
        return collect(
            preg_split('/[\r\n]+/', $this->process->getOutput())
        )->reject(function ($line) {
            return Str::contains($line, [
                // "INFO\tListening on ",
                // "INFO\tRunning command",
                // "WARN\tLoading extension",
                // "INFO\tMarionette enabled",
                // 'No settings file exists, new profile?',
                // 'failed mapping default framebuffer',
            ]);
        })->implode("\n");
    }
```

Then running `php artisan dusk` will show that output in the `tests/Browser/console/*.log` files.

I tried this without setting up the `FirefoxProfile` object and it looks like "php-webdriver/webdriver" v1.11.0 & Geckodriver _do_ still setup a temporary Firefox profile for tests. i.e., the .log file shows command line argument `-profile /tmp/mozprofileetc` being sent to the Firefox binary.

Digging into https://github.com/php-webdriver/php-webdriver/issues & https://github.com/mozilla/geckodriver/issues this seems to be an issue with Firefox Portable (https://github.com/mozilla/geckodriver/issues/1443) or older releases. I started this package in June 2020 so only Firefox 76 or above have been tested. https://github.com/php-webdriver/php-webdriver/blob/main/README.md#b-geckodriver & https://github.com/php-webdriver/php-webdriver/wiki/Firefox#installation indicate the latest Firefox & Geckodriver should always be used. So currently that would be Firefox 90 and Geckodriver 0.29.1 (`php artisan dusk:firefox-driver` grabs the latter).

**Comment by torian257x** [comment]
thanks for your comments!

I found out following solution:
don't install firefox using snap

Maybe I was crazy for trying to do that? but I had bad experiences with ubuntus apt manager and installing chrome (would install old versions or was hard to get an updated version). Thats why I chose snapd.

I followed this installation guide using snapd
https://idroot.us/install-firefox-ubuntu-20-04/

I uninstalled it using snapd



reinstalled the "normal" ubuntu way

>Install Firefox from the Ubuntu repository.
>Run the following command in a terminal to install it:
>`sudo apt install firefox`

and it seems to work

commenting out the lines in getOutput btw did nothing (no output in console directory)

**Comment by torian257x** [comment]
I just wanted to thank you for this project. I had a lot of issues with chrome crashing, and they seem to all went away with your firefox implementation @derekmd 

I will leave some of the chrome errors here so people can potentially find this thread and your firefox solution.


Common chrome errors I had were:

>Chrome failed to start: exited abnormally
>unkown error devtoolsactiveport file doesn't exist

> Facebook\WebDriver\Exception\UnknownErrorException: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)


> Facebook\WebDriver\Exception\UnknownErrorException: unknown error: session deleted because of page crash
 from unknown error: cannot determine loading status
from tab crashed

>Operation timed out after 30008 milliseconds with 0 bytes received
